title: Mirko in Brasilien
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap #  - jekyll-include-cache - jekyll-archives


jekyll-archives:
  enabled:
    - categories
    - tags
    - yearly
    - monthly
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    yearly: '/:year/'
    monthly: '/:year/:month/'
sass:
  style: compressed

service_worker_enabled: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      css: "assets/css/style.scss"
      image: "{{ 'assets/img/seo.jpg' | relative_url }}"  # Default Bild
      lang: "de_DE"
      author: "Leggravi"
      description: "Mirko in Brasilien - Ein Blog über meine Erfahrungen und Erlebnisse während meines Kurzzeiteinsatzes in der Missionsstation Alves de Barros in Brasilien."
