title: Mirko in Brasilien
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed
service_worker_enabled: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      css: "assets/css/style.scss"
